### ISSUE TITLE
how to build without cuda

### ISSUE THREAD

**Issue by anguoyang** [prabindh/darknet-cpp-windows#1]
hi, i want to build it without cuda under windows/visual studio, but it seems the project file has no options on it

**Comment by prabindh** [comment]
You can refer to the options in the darknet project: {GPU;CUDNN;PTHREAD_WINDOWS;}
GPU defined ==> CUDA being used.
If GPU not defined, you need to remove CUDNN also.
Both darknet and arapaho projects need to have the same project options.

**Comment by anguoyang** [comment]
ok, thank you, is the darknet project this one?:
https://github.com/prabindh/darknet

or the original darknet?

**Comment by anguoyang** [comment]
i want to run darknet/windows with opencl only, no gpu, is it possible?

**Comment by prabindh** [comment]
It is this, https://github.com/prabindh/darknet, as the original version does not build on Windows. But, it has the same code-base, modified for Windows.
Note: The latest changes in the mainline are reflected in an integration branch of the above project, not main branch.

**Comment by prabindh** [comment]
@anguoyang OpenCL port is not available yet. Only CUDA with GPU.

**Comment by anguoyang** [comment]
however, I found related document and source code in the repo

**Comment by prabindh** [comment]
@anguoyang could you please point me to where you found OpenCL references ?

**Comment by anguoyang** [comment]
@prabindh i found the description here:
https://github.com/myestro/darknet

**Comment by prabindh** [comment]
@anguoyang  Closing this issue.

**Comment by zhangcj13** [comment]
> You can refer to the options in the darknet project: {GPU;CUDNN;PTHREAD_WINDOWS;}
> GPU defined ==> CUDA being used.
> If GPU not defined, you need to remove CUDNN also.
> Both darknet and arapaho projects need to have the same project options.

is this set in the vs2015  project/darknet property page, could you show the details? i can't find this seting. thanks!

**Comment by prabindh** [comment]
![darknet-vs1](https://user-images.githubusercontent.com/1215029/48992967-cdff1180-f160-11e8-94cb-4103bc75d648.png)

Please check attached image
