### ISSUE TITLE
Visual Studio 2015 and OpenCV 3.2.0

### ISSUE THREAD

**Issue by Dezorian** [prabindh/darknet-cpp-windows#2]
To get it working with Visual Studio 2015 and OpenCV 3.2.0 , I had to change the following items:

Arapaho project properties:
- pthread.h -> change (comment out) the timespec (which is available in time.h):
`/*struct timespec
{	
	long long tv_sec;
	long long tv_nsec;
};*/` 
Without this change I got error for redeclared timespec struct.
- pthread.h -> add time.h to the includes: `#include <time.h>`
- Linker -> General -> Additional Library Directories -> change [..\..\opencv3\build\x64\vc12\lib] to [..\..\opencv3\build\x64\vc14\lib]  (so change **vc12** to **vc14** )
- Linker -> Input -> Additional Dependencies -> change **opencv_world310.lib** to **opencv_world320.lib**

**Comment by prabindh** [comment]
Thanks a lot. Will you have a patch, or do you want me to push (I have these same changes pending for quite a while, along with some additional ones)

**Comment by Dezorian** [comment]
No need, I have a building setup now. So maybe push the changes, so other ppl can enjoy them as well. Maybe it's a good thing to write down the dependency links so users can change them if they use a different version of OpenCV/VS?
