### ISSUE TITLE
Unresolved link to a "genesisarapaho" project in the solution..

### ISSUE THREAD

**Issue by hpverweij** [prabindh/darknet-cpp-windows#3]
This project is not in the repository..

Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "genesisarapaho", "..\genesisarapaho\genesisarapaho.vcxproj", "{D1034CB0-C145-4407-BB89-DDDA8FD9C54E}"
EndProject

**Comment by prabindh** [comment]
@hpverweij  - Updated solution, please check...

**Comment by dickverweij** [comment]
got it all working !!..
