### ISSUE TITLE
No Detection with Custom Models

### ISSUE THREAD

**Issue by Optimus1072** [prabindh/darknet-cpp-windows#5]
Hi, I trained custom models and when I tested those models with original darknet C code everything seems to work fine. I am getting proper detection results. But when I use same config/weights with this C++ extension I am getting 0 detections.

Note : This C++ wrapper is working properly with the pretrained YOLO(both tiny and full) models,  the problem persists only when trained on custom dataset. I even tried keeping the config file same and then training on custom dataset, even then I am getting zero detections.

**Comment by Optimus1072** [comment]
Further, I would like to add that I haven't trained using the C++ API(if there is an option in it). Training was done using the original C code

**Comment by prabindh** [comment]
Could you confirm - if the same code-base is used for training (on Linux, as Windows training is not supported yet) ?

**Comment by Optimus1072** [comment]
No I have used the original code from darknet for training and C++ wrapper for testing. Yes everything is on Linux. Do you thing I should train also with this wrapper?
Sorry for the late reply.

**Comment by prabindh** [comment]
If you had trained with the latest darknet (original code), it could be an issue with the weight versions. Could you please train with the same code-base, then use the C++ wrapper ? For reference on this, see https://github.com/prabindh/darknet/issues/54

**Comment by prabindh** [comment]
The code-base is now validated with Yolov3 as well.  Closing.
