### ISSUE TITLE
Common folder from the NVIDIA GPU Computing Toolkit missing

### ISSUE THREAD

**Issue by IlSaCCo** [prabindh/darknet-cpp-windows#6]
Hi I am having some trouble with the setup,
I would like to use the project with CUDA v9.1 + CUDNN v7.1. Unfortunately in this new version the common folder is no longer there.
Is there a workaround for this?

Thanks
L

**Comment by prabindh** [comment]
The common/inc should not be needed in the new builds, are you able to build without this folder ?

**Comment by prabindh** [comment]
Please check latest solution file in the master. The dependency is removed.
