### ISSUE TITLE
compile the release model failed

### ISSUE THREAD

**Issue by apple1987** [prabindh/darknet-cpp-windows#7]
rt .u provide is debug model ,why commit the release model? i try it failed,thanks!

**Comment by prabindh** [comment]
Thank you for reporting. This should be addressed in the master, via 2b4b49fcb1b700eb24f1eae9aeaf996ea219a79c

**Comment by prabindh** [comment]
Please close the issue after verification. Thanks.

**Comment by prabindh** [comment]
Any update @apple1987 ?
