### ISSUE TITLE
Huge RAM usage

### ISSUE THREAD

**Issue by lukaszkepka** [prabindh/darknet-cpp-windows#8]
Hello,

I have runned arapaho.exe with YOLOv3 configuration. Everything works perfectly, but after loading network process memory reaches up to 3,2 GB (!). Is that normal behaviour?

**Comment by prabindh** [comment]
What is the input image resolution, and what is the .cfg used ?

**Comment by lukaszkepka** [comment]
I'm using image resolution 416x416 and configuration from https://github.com/pjreddie/darknet/blob/master/cfg/yolov3-voc.cfg. To rectify, 3,2 GB appears in Visual Studio Diagnostic Tools. Without debugger attached process takes 1,5 GB RAM (value from task manager)

**Comment by prabindh** [comment]
I suspect the exe might be running within Visual Studio - can this be run independently (ex, from command line) and the memory checked again ?

**Comment by lukaszkepka** [comment]
When application is running as standalone, RAM usage is about 1,5 GB. Do you have similar results on your machine?

**Comment by prabindh** [comment]
Yes...BTW, the GPU usage is documented at (for yolov2) - https://github.com/prabindh/darknet/blob/master/arapaho/Arapaho-GPU-Z%20Sensor-Log.txt.
The yolov3 usage is higher.

**Comment by lukaszkepka** [comment]
Ok, i have also checked newest implementation of YOLO3 in OpenCV. It also takes ~1,5 GB so i guess that everything is ok. Thanks for your help!
