### ISSUE TITLE
how do i get these data (input.cfg, input.data, input.jpg or input.mp4, input.weights)

### ISSUE THREAD

**Issue by zhangcj13** [prabindh/darknet-cpp-windows#9]
do these data have examples in the darknet project  or  i need train to get these data.

**Comment by prabindh** [comment]
Yes, these can be your own cfg/weights if trained already. For reference, they can be taken from darknet project - like https://github.com/prabindh/darknet/blob/master/cfg/yolov3-tiny.cfg, along with the pre-trained weight file.

**Comment by prabindh** [comment]
Pretrained weights can be obtained from https://pjreddie.com/darknet/yolo/

**Comment by zhangcj13** [comment]
> Pretrained weights can be obtained from https://pjreddie.com/darknet/yolo/

got it, thanks for your reply
